### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/cpp11bigwig#5]
- [x] Collapse single-base intervals to interval spans (e.g., bedGraph)
- [x] Implement CURL call-backs (available in libBigWig)
- [x] Implement `read_bigbed()`
